// <auto-generated />
using System;
using MatchIQ.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MatchIQ.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260629010345_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MatchIQ.Domain.Entities.CandidateCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer")
                        .HasColumnName("candidate_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("idx_candidate_categories");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CandidateId", "CategoryId")
                        .IsUnique();

                    b.ToTable("candidate_categories", (string)null);
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.CandidateProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EnglishLevel")
                        .HasColumnType("text")
                        .HasColumnName("english_level");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("integer")
                        .HasColumnName("experience_years");

                    b.Property<string>("GithubLink")
                        .HasColumnType("text")
                        .HasColumnName("github_link");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("profile_photo_url");

                    b.Property<string>("Seniority")
                        .HasColumnType("text")
                        .HasColumnName("seniority");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("candidate_profiles", null, t =>
                        {
                            t.HasCheckConstraint("ck_candidate_profiles_experience_years", "experience_years >= 0");
                        });
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.CandidateSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer")
                        .HasColumnName("candidate_id");

                    b.Property<int?>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_id");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("idx_candidate_skills");

                    b.HasIndex("SkillId");

                    b.HasIndex("CandidateId", "SkillId")
                        .IsUnique();

                    b.ToTable("candidate_skills", null, t =>
                        {
                            t.HasCheckConstraint("ck_candidate_skills_level", "level BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.CompanyProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("company_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("company_profiles", (string)null);
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.EmailVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("expires_at");

                    b.Property<bool>("Used")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("used");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Used")
                        .HasDatabaseName("idx_email_verifications_user");

                    b.ToTable("email_verifications", (string)null);
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.JobOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidatesTestedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("candidates_tested_count");

                    b.Property<int?>("CandidatesToTest")
                        .HasColumnType("integer")
                        .HasColumnName("candidates_to_test");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("expires_at");

                    b.Property<int?>("MinExperienceYears")
                        .HasColumnType("integer")
                        .HasColumnName("min_experience_years");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modality");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("paid_at");

                    b.Property<int>("PositionsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("positions_available");

                    b.Property<string>("RequiredEnglishLevel")
                        .HasColumnType("text")
                        .HasColumnName("required_english_level");

                    b.Property<decimal?>("Salary")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("salary");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("PendingPayment")
                        .HasColumnName("status");

                    b.Property<DateTime?>("TestSentAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("test_sent_at");

                    b.Property<int>("TierId")
                        .HasColumnType("integer")
                        .HasColumnName("tier_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("idx_offers_company_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_offers_test_sent_status")
                        .HasFilter("status = 'TestSent'");

                    b.HasIndex("TierId")
                        .HasDatabaseName("idx_offers_tier_id");

                    b.ToTable("job_offers", null, t =>
                        {
                            t.HasCheckConstraint("ck_job_offers_candidates_tested_count", "candidates_tested_count >= 0");

                            t.HasCheckConstraint("ck_job_offers_candidates_to_test", "candidates_to_test IS NULL OR candidates_to_test > 0");

                            t.HasCheckConstraint("ck_job_offers_min_experience_years", "min_experience_years >= 0");

                            t.HasCheckConstraint("ck_job_offers_positions_available", "positions_available > 0");
                        });
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AdjustedScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("adjusted_score");

                    b.Property<string>("AiFeedback")
                        .HasColumnType("jsonb")
                        .HasColumnName("ai_feedback");

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer")
                        .HasColumnName("candidate_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("MatchPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("match_percentage");

                    b.Property<int>("OfferId")
                        .HasColumnType("integer")
                        .HasColumnName("offer_id");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Matched")
                        .HasColumnName("stage");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("idx_matches_candidate_id");

                    b.HasIndex("OfferId")
                        .HasDatabaseName("idx_matches_offer_id");

                    b.HasIndex("OfferId", "CandidateId")
                        .IsUnique();

                    b.HasIndex("OfferId", "Stage")
                        .HasDatabaseName("idx_matches_stage");

                    b.ToTable("matches", null, t =>
                        {
                            t.HasCheckConstraint("ck_matches_adjusted_score", "adjusted_score BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_matches_match_percentage", "match_percentage BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.OfferCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<int>("OfferId")
                        .HasColumnType("integer")
                        .HasColumnName("offer_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OfferId")
                        .HasDatabaseName("idx_offer_categories");

                    b.HasIndex("OfferId", "CategoryId")
                        .IsUnique();

                    b.ToTable("offer_categories", (string)null);
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.OfferSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OfferId")
                        .HasColumnType("integer")
                        .HasColumnName("offer_id");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_id");

                    b.HasKey("Id");

                    b.HasIndex("OfferId")
                        .HasDatabaseName("idx_offer_skills");

                    b.HasIndex("SkillId");

                    b.HasIndex("OfferId", "SkillId")
                        .IsUnique();

                    b.ToTable("offer_skills", (string)null);
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<bool>("Used")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("used");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("idx_password_reset_token");

                    b.HasIndex("UserId");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountCop")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount_cop");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("OfferId")
                        .HasColumnType("integer")
                        .HasColumnName("offer_id");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("paid_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<string>("StripeCheckoutSessionId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stripe_checkout_session_id");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stripe_payment_intent_id");

                    b.Property<int>("TierId")
                        .HasColumnType("integer")
                        .HasColumnName("tier_id");

                    b.HasKey("Id");

                    b.HasIndex("OfferId")
                        .IsUnique()
                        .HasDatabaseName("idx_payments_offer_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_payments_status");

                    b.HasIndex("StripeCheckoutSessionId")
                        .IsUnique();

                    b.HasIndex("StripePaymentIntentId")
                        .IsUnique()
                        .HasDatabaseName("idx_payments_stripe_intent");

                    b.HasIndex("TierId");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.PricingTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("MaxCandidates")
                        .HasColumnType("integer")
                        .HasColumnName("max_candidates");

                    b.Property<int>("MinCandidates")
                        .HasColumnType("integer")
                        .HasColumnName("min_candidates");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<decimal>("PriceCop")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price_cop");

                    b.HasKey("Id");

                    b.ToTable("pricing_tiers", null, t =>
                        {
                            t.HasCheckConstraint("ck_pricing_tiers_max_candidates", "max_candidates >= min_candidates");

                            t.HasCheckConstraint("ck_pricing_tiers_min_candidates", "min_candidates > 0");

                            t.HasCheckConstraint("ck_pricing_tiers_price_cop", "price_cop >= 0");
                        });
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.QuestionChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("idx_chat_messages_question_id");

                    b.ToTable("question_chat_messages", (string)null);
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("expires_at");

                    b.Property<bool>("Revoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("revoked");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("idx_refresh_tokens_token");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name", "CategoryId")
                        .IsUnique();

                    b.ToTable("skills", (string)null);
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("OfferId")
                        .HasColumnType("integer")
                        .HasColumnName("offer_id");

                    b.Property<int>("TimeLimitMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30)
                        .HasColumnName("time_limit_minutes");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("OfferId")
                        .IsUnique()
                        .HasDatabaseName("idx_tests_offer_id");

                    b.ToTable("tests", null, t =>
                        {
                            t.HasCheckConstraint("ck_tests_time_limit_minutes", "time_limit_minutes > 0");
                        });
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.TestQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectAnswer")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("correct_answer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ExampleInput")
                        .HasColumnType("text")
                        .HasColumnName("example_input");

                    b.Property<string>("ExpectedBehavior")
                        .HasColumnType("text")
                        .HasColumnName("expected_behavior");

                    b.Property<string>("Explanation")
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<string>("FunctionSignature")
                        .HasColumnType("text")
                        .HasColumnName("function_signature");

                    b.Property<string>("GorillaHint")
                        .HasColumnType("text")
                        .HasColumnName("gorilla_hint");

                    b.Property<bool>("IsGorilla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_gorilla");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("language");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("options_json");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_type");

                    b.Property<int>("TestId")
                        .HasColumnType("integer")
                        .HasColumnName("test_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("TestId")
                        .HasDatabaseName("idx_questions_test_id");

                    b.HasIndex("TestId", "OrderIndex")
                        .IsUnique();

                    b.ToTable("test_questions", null, t =>
                        {
                            t.HasCheckConstraint("ck_test_questions_order_index", "order_index > 0");
                        });
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.TestSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AiEvaluatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("ai_evaluated_at");

                    b.Property<string>("AnswersJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("answers_json");

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer")
                        .HasColumnName("candidate_id");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp")
                        .HasColumnName("deadline");

                    b.Property<string>("Feedback")
                        .HasColumnType("text")
                        .HasColumnName("feedback");

                    b.Property<decimal?>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("score");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("submitted_at");

                    b.Property<int>("TestId")
                        .HasColumnType("integer")
                        .HasColumnName("test_id");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("idx_submissions_candidate_id");

                    b.HasIndex("Deadline")
                        .HasDatabaseName("idx_submissions_deadline")
                        .HasFilter("status = 'Pending'");

                    b.HasIndex("TestId")
                        .HasDatabaseName("idx_submissions_test_id");

                    b.HasIndex("TestId", "CandidateId")
                        .IsUnique();

                    b.ToTable("test_submissions", null, t =>
                        {
                            t.HasCheckConstraint("ck_test_submissions_score", "score BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("google_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("text")
                        .HasColumnName("picture_url");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasFilter("google_id IS NOT NULL");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.CandidateCategory", b =>
                {
                    b.HasOne("MatchIQ.Domain.Entities.CandidateProfile", "CandidateProfile")
                        .WithMany("CandidateCategories")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatchIQ.Domain.Entities.Category", "Category")
                        .WithMany("CandidateCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.CandidateProfile", b =>
                {
                    b.HasOne("MatchIQ.Domain.Entities.User", "User")
                        .WithOne("CandidateProfile")
                        .HasForeignKey("MatchIQ.Domain.Entities.CandidateProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.CandidateSkill", b =>
                {
                    b.HasOne("MatchIQ.Domain.Entities.CandidateProfile", "CandidateProfile")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatchIQ.Domain.Entities.Skill", "Skill")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.CompanyProfile", b =>
                {
                    b.HasOne("MatchIQ.Domain.Entities.User", "User")
                        .WithOne("CompanyProfile")
                        .HasForeignKey("MatchIQ.Domain.Entities.CompanyProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.EmailVerification", b =>
                {
                    b.HasOne("MatchIQ.Domain.Entities.User", "User")
                        .WithMany("EmailVerifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.JobOffer", b =>
                {
                    b.HasOne("MatchIQ.Domain.Entities.CompanyProfile", "CompanyProfile")
                        .WithMany("JobOffers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatchIQ.Domain.Entities.PricingTier", "PricingTier")
                        .WithMany("JobOffers")
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyProfile");

                    b.Navigation("PricingTier");
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.Match", b =>
                {
                    b.HasOne("MatchIQ.Domain.Entities.CandidateProfile", "CandidateProfile")
                        .WithMany("Matches")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatchIQ.Domain.Entities.JobOffer", "JobOffer")
                        .WithMany("Matches")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");

                    b.Navigation("JobOffer");
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.OfferCategory", b =>
                {
                    b.HasOne("MatchIQ.Domain.Entities.Category", "Category")
                        .WithMany("OfferCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatchIQ.Domain.Entities.JobOffer", "JobOffer")
                        .WithMany("OfferCategories")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("JobOffer");
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.OfferSkill", b =>
                {
                    b.HasOne("MatchIQ.Domain.Entities.JobOffer", "JobOffer")
                        .WithMany("OfferSkills")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatchIQ.Domain.Entities.Skill", "Skill")
                        .WithMany("OfferSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobOffer");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("MatchIQ.Domain.Entities.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.Payment", b =>
                {
                    b.HasOne("MatchIQ.Domain.Entities.JobOffer", "JobOffer")
                        .WithOne("Payment")
                        .HasForeignKey("MatchIQ.Domain.Entities.Payment", "OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatchIQ.Domain.Entities.PricingTier", "PricingTier")
                        .WithMany("Payments")
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobOffer");

                    b.Navigation("PricingTier");
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.QuestionChatMessage", b =>
                {
                    b.HasOne("MatchIQ.Domain.Entities.TestQuestion", "TestQuestion")
                        .WithMany("QuestionChatMessages")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestQuestion");
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("MatchIQ.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.Skill", b =>
                {
                    b.HasOne("MatchIQ.Domain.Entities.Category", "Category")
                        .WithMany("Skills")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.Test", b =>
                {
                    b.HasOne("MatchIQ.Domain.Entities.JobOffer", "JobOffer")
                        .WithOne("Test")
                        .HasForeignKey("MatchIQ.Domain.Entities.Test", "OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobOffer");
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.TestQuestion", b =>
                {
                    b.HasOne("MatchIQ.Domain.Entities.Test", "Test")
                        .WithMany("TestQuestions")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.TestSubmission", b =>
                {
                    b.HasOne("MatchIQ.Domain.Entities.CandidateProfile", "CandidateProfile")
                        .WithMany("TestSubmissions")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatchIQ.Domain.Entities.Test", "Test")
                        .WithMany("TestSubmissions")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.CandidateProfile", b =>
                {
                    b.Navigation("CandidateCategories");

                    b.Navigation("CandidateSkills");

                    b.Navigation("Matches");

                    b.Navigation("TestSubmissions");
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.Category", b =>
                {
                    b.Navigation("CandidateCategories");

                    b.Navigation("OfferCategories");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.CompanyProfile", b =>
                {
                    b.Navigation("JobOffers");
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.JobOffer", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("OfferCategories");

                    b.Navigation("OfferSkills");

                    b.Navigation("Payment");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.PricingTier", b =>
                {
                    b.Navigation("JobOffers");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.Skill", b =>
                {
                    b.Navigation("CandidateSkills");

                    b.Navigation("OfferSkills");
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.Test", b =>
                {
                    b.Navigation("TestQuestions");

                    b.Navigation("TestSubmissions");
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.TestQuestion", b =>
                {
                    b.Navigation("QuestionChatMessages");
                });

            modelBuilder.Entity("MatchIQ.Domain.Entities.User", b =>
                {
                    b.Navigation("CandidateProfile");

                    b.Navigation("CompanyProfile");

                    b.Navigation("EmailVerifications");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
